import { z } from "zod";
import { existsSync, unlinkSync } from "node:fs";
import { join } from "node:path";
import type { ServerContext } from "../context.js";
import type { WriteMode } from "../context.js";
import { err, ok, ToolResult } from "./result.js";
import {
  loadYamlRuleFile,
  writeYamlRuleFile,
  type YamlRule,
  type YamlProperty,
} from "../../lib/yaml-transform.js";
import { PlanNotFoundError } from "../../lib/plans-config.js";
import {
  createBranch,
  commitPaths,
  pushBranch,
  openPullRequest,
  GitOpsError,
} from "../../lib/git-ops.js";

const yamlPropertySchema: z.ZodType<YamlProperty> = z
  .object({
    type: z.string().optional(),
    description: z.string().optional(),
    required: z.boolean().optional(),
  })
  .catchall(z.unknown());

export const addEventInput = z
  .object({
    plan: z.string(),
    key: z.string(),
    type: z.string().optional(),
    version: z.number().int().positive().optional(),
    description: z.string(),
    properties: z.record(yamlPropertySchema),
    labels: z.record(z.string()).optional(),
    mode: z.enum(["files", "branch", "pr"]).optional(),
  })
  .strict();

export const updateEventInput = z
  .object({
    plan: z.string(),
    key: z.string(),
    changes: z
      .object({
        description: z.string().optional(),
        add_properties: z.record(yamlPropertySchema).optional(),
        update_properties: z.record(yamlPropertySchema).optional(),
        remove_properties: z.array(z.string()).optional(),
        labels: z.record(z.string()).optional(),
      })
      .strict(),
    mode: z.enum(["files", "branch", "pr"]).optional(),
  })
  .strict();

export const removeEventInput = z
  .object({
    plan: z.string(),
    key: z.string(),
    confirm: z.literal(true),
    mode: z.enum(["files", "branch", "pr"]).optional(),
  })
  .strict();

function planYamlPath(repoPath: string, planPath: string, key: string): string {
  const fileName = `${key.replace(/ /g, "_")}.yml`;
  return join(repoPath, "tracking-rules", planPath, fileName);
}

interface WriteOutput {
  files_changed: string[];
  mode: WriteMode;
  branch?: string;
  commit_sha?: string;
  pr_url?: string;
  pr_number?: number;
  next_steps?: string;
  [k: string]: unknown;
}

interface MutatorResult {
  files_changed: string[];
  extras?: Record<string, unknown>;
}

function slugify(key: string): string {
  return key.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

function branchName(planPath: string, key: string, verb: string, now: number): string {
  return `tp/${planPath}/${verb}-${slugify(key)}-${now}`;
}

export async function applyWriteFlow(
  ctx: ServerContext,
  planPath: string,
  _planName: string,
  key: string,
  verb: "add" | "update" | "remove",
  mode: WriteMode,
  mutator: () => MutatorResult,
  now: number = Date.now(),
): Promise<ToolResult<WriteOutput>> {
  const pre = ctx.preflightWrite(mode);
  if (pre.blocked) return { ok: false, error: pre.error };

  if (mode === "files") {
    const { files_changed, extras } = mutator();
    return ok({ files_changed, mode, ...(extras ?? {}) });
  }

  const branch = branchName(planPath, key, verb, now);
  try {
    createBranch(ctx.repoPath, branch);
    const { files_changed, extras } = mutator();
    const commitMessage =
      `[tp:${planPath}] ${verb} event "${key}"\n\n` +
      `- Generated via tracking-plans-mcp`;
    const commit_sha = commitPaths(ctx.repoPath, files_changed, commitMessage);

    if (mode === "branch") {
      return ok({
        files_changed,
        mode,
        branch,
        commit_sha,
        next_steps: `git push -u origin ${branch} && open PR`,
        ...(extras ?? {}),
      });
    }

    // pr mode
    pushBranch(ctx.repoPath, branch);
    const pr = await openPullRequest(ctx.repoPath, {
      branch,
      title: `[tp:${planPath}] ${verb} event "${key}"`,
      body: `Generated by tracking-plans-mcp.\n\nFiles changed:\n${files_changed
        .map((f) => `- \`${f}\``)
        .join("\n")}`,
    });
    return ok({
      files_changed,
      mode,
      branch,
      commit_sha,
      pr_url: pr.pr_url,
      pr_number: pr.pr_number,
      ...(extras ?? {}),
    });
  } catch (e) {
    if (e instanceof GitOpsError) {
      return { ok: false, error: { code: e.code, message: e.message, details: e.details } };
    }
    throw e;
  }
}

export async function addEvent(
  ctx: ServerContext,
  args: z.infer<typeof addEventInput>,
): Promise<ToolResult<WriteOutput>> {
  const mode = ctx.resolveWriteMode(args.mode);
  const pre = ctx.preflightWrite(mode);
  if (pre.blocked) return { ok: false, error: pre.error };
  let plan;
  try {
    plan = ctx.resolvePlanOrThrow(args.plan);
  } catch (e) {
    if (e instanceof PlanNotFoundError) return err("NOT_FOUND", e.message);
    throw e;
  }
  const filePath = planYamlPath(ctx.repoPath, plan.path, args.key);
  const relPath = `tracking-rules/${plan.path}/${args.key.replace(/ /g, "_")}.yml`;
  if (existsSync(filePath)) {
    return err(
      "VALIDATION",
      `Event "${args.key}" already exists at ${filePath}. Use update_event to modify.`,
    );
  }
  return applyWriteFlow(ctx, plan.path, plan.name, args.key, "add", mode, () => {
    const yamlRule: YamlRule = {
      key: args.key,
      type: args.type ?? "TRACK",
      version: args.version ?? 1,
      description: args.description,
      properties: args.properties,
    };
    if (args.labels) yamlRule.labels = args.labels;
    writeYamlRuleFile(filePath, yamlRule);
    return { files_changed: [relPath] };
  });
}

export async function updateEvent(
  ctx: ServerContext,
  args: z.infer<typeof updateEventInput>,
): Promise<ToolResult<WriteOutput>> {
  const mode = ctx.resolveWriteMode(args.mode);
  const pre = ctx.preflightWrite(mode);
  if (pre.blocked) return { ok: false, error: pre.error };
  let plan;
  try {
    plan = ctx.resolvePlanOrThrow(args.plan);
  } catch (e) {
    if (e instanceof PlanNotFoundError) return err("NOT_FOUND", e.message);
    throw e;
  }
  const filePath = planYamlPath(ctx.repoPath, plan.path, args.key);
  if (!existsSync(filePath)) {
    return err("NOT_FOUND", `Event "${args.key}" has no yaml file at ${filePath}.`);
  }
  // Validate changes before entering write flow
  const current = loadYamlRuleFile(filePath);
  if (args.changes.add_properties) {
    for (const [name] of Object.entries(args.changes.add_properties)) {
      if (current.properties[name]) {
        return err(
          "VALIDATION",
          `Property "${name}" already exists on "${args.key}"; use update_properties instead.`,
        );
      }
    }
  }
  if (args.changes.update_properties) {
    for (const [name] of Object.entries(args.changes.update_properties)) {
      if (!current.properties[name]) {
        return err(
          "NOT_FOUND",
          `Property "${name}" not found on "${args.key}"; use add_properties.`,
        );
      }
    }
  }
  const relPath = `tracking-rules/${plan.path}/${args.key.replace(/ /g, "_")}.yml`;
  return applyWriteFlow(ctx, plan.path, plan.name, args.key, "update", mode, () => {
    // Re-load inside mutator so branch mode reads the file on the new branch
    const rule = loadYamlRuleFile(filePath);
    if (args.changes.description !== undefined) rule.description = args.changes.description;
    if (args.changes.labels !== undefined) rule.labels = args.changes.labels;
    if (args.changes.add_properties) {
      for (const [name, prop] of Object.entries(args.changes.add_properties)) {
        rule.properties[name] = prop;
      }
    }
    if (args.changes.update_properties) {
      for (const [name, patch] of Object.entries(args.changes.update_properties)) {
        rule.properties[name] = { ...rule.properties[name], ...patch };
      }
    }
    if (args.changes.remove_properties) {
      for (const name of args.changes.remove_properties) {
        delete rule.properties[name];
      }
    }
    writeYamlRuleFile(filePath, rule);
    return { files_changed: [relPath] };
  });
}

export async function removeEvent(
  ctx: ServerContext,
  args: z.infer<typeof removeEventInput>,
): Promise<ToolResult<WriteOutput & { removed_yaml: YamlRule }>> {
  const parsed = removeEventInput.safeParse(args);
  if (!parsed.success) {
    return err("VALIDATION", parsed.error.message);
  }
  const mode = ctx.resolveWriteMode(args.mode);
  const pre = ctx.preflightWrite(mode);
  if (pre.blocked) return { ok: false, error: pre.error };
  let plan;
  try {
    plan = ctx.resolvePlanOrThrow(args.plan);
  } catch (e) {
    if (e instanceof PlanNotFoundError) return err("NOT_FOUND", e.message);
    throw e;
  }
  const filePath = planYamlPath(ctx.repoPath, plan.path, args.key);
  if (!existsSync(filePath)) {
    return err("NOT_FOUND", `Event "${args.key}" has no yaml file at ${filePath}.`);
  }
  const relPath = `tracking-rules/${plan.path}/${args.key.replace(/ /g, "_")}.yml`;
  return applyWriteFlow(ctx, plan.path, plan.name, args.key, "remove", mode, () => {
    const removed = loadYamlRuleFile(filePath);
    unlinkSync(filePath);
    return { files_changed: [relPath], extras: { removed_yaml: removed } };
  }) as Promise<ToolResult<WriteOutput & { removed_yaml: YamlRule }>>;
}
