import type { ServerContext, WriteMode } from "../context.js";
import { ok, err, ToolResult } from "./result.js";
import {
  createBranch,
  commitPaths,
  pushBranch,
  openPullRequest,
  GitOpsError,
  getWorkingTreeStatus,
  checkoutBranch,
  deleteBranch,
  discardWorkingTreeChanges,
} from "../../lib/git-ops.js";

export interface WriteOutput {
  files_changed: string[];
  mode: WriteMode;
  branch?: string;
  commit_sha?: string;
  pr_url?: string;
  pr_number?: number;
  next_steps?: string;
  [k: string]: unknown;
}

export interface MutatorResult {
  files_changed: string[];
  extras?: Record<string, unknown>;
}

export function slugify(key: string): string {
  return key.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

export type WriteVerb = "add" | "update" | "remove" | "reset" | "pull";

/**
 * Commit subject. Event verbs: `<verb> event "<key>"`. Admin verbs ("reset",
 * "pull") treat `key` as a free-form object, e.g. `pull prod snapshot`.
 */
export function commitSubject(planPath: string, verb: WriteVerb, key: string): string {
  const body =
    verb === "reset" || verb === "pull" ? `${verb} ${key}` : `${verb} event "${key}"`;
  return `[tp:${planPath}] ${body}`;
}

export function branchName(planPath: string, key: string, verb: string, now: number): string {
  return `tp/${planPath}/${verb}-${slugify(key)}-${now}`;
}

/**
 * Core write-flow for all mutating MCP tools.
 *
 * - "files" mode: run the mutator inline, no git branch/commit.
 * - "branch" / "pr" mode:
 *   1. Record the current branch so we can restore it afterwards.
 *   2. Create a tp/… branch.
 *   3. Run the mutator.  If it returns no files (Fix 3), tear down the branch
 *      and return ok with a warning rather than attempting an empty commit.
 *   4. Commit (and push / open PR for pr mode).
 *   5. `finally`: always restore the original branch so the caller's working
 *      tree is left where it started (Fix 1).
 *   6. `catch`: on any error, discard partial on-disk writes and also delete
 *      the tp branch to avoid leaving ghost branches (Fix 2).
 */
export async function applyWriteFlow(
  ctx: ServerContext,
  planPath: string,
  _planName: string,
  key: string,
  verb: WriteVerb,
  mode: WriteMode,
  mutator: () => MutatorResult,
  now: number = Date.now(),
): Promise<ToolResult<WriteOutput>> {
  const pre = ctx.preflightWrite(mode);
  if (pre.blocked) return { ok: false, error: pre.error };

  if (mode === "files") {
    const { files_changed, extras } = mutator();
    return ok({ files_changed, mode, ...(extras ?? {}) });
  }

  const originalBranch = getWorkingTreeStatus(ctx.repoPath).current_branch;
  const newBranch = branchName(planPath, key, verb, now);
  let branchCreated = false;
  let hadError = false;

  try {
    createBranch(ctx.repoPath, newBranch);
    branchCreated = true;

    const { files_changed, extras } = mutator();

    // Fix 3: zero-affected short-circuit — no commit, no branch left behind
    if (files_changed.length === 0) {
      try { checkoutBranch(ctx.repoPath, originalBranch); } catch { /* best effort */ }
      try { deleteBranch(ctx.repoPath, newBranch); } catch { /* best effort */ }
      branchCreated = false;
      return ok(
        { files_changed: [], mode, ...(extras ?? {}) },
        ["No files matched — no changes to commit."],
      );
    }

    const subject = commitSubject(planPath, verb, key);
    const commitMessage =
      `${subject}\n\n` +
      `- Generated via tracking-plans-mcp`;
    const commit_sha = commitPaths(ctx.repoPath, files_changed, commitMessage);

    if (mode === "branch") {
      return ok({
        files_changed,
        mode,
        branch: newBranch,
        commit_sha,
        next_steps: `git push -u origin ${newBranch} && open PR`,
        ...(extras ?? {}),
      });
    }

    // pr mode
    pushBranch(ctx.repoPath, newBranch);
    const pr = await openPullRequest(ctx.repoPath, {
      branch: newBranch,
      title: subject,
      body: `Generated by tracking-plans-mcp.\n\nFiles changed:\n${files_changed
        .map((f) => `- \`${f}\``)
        .join("\n")}`,
    });
    return ok({
      files_changed,
      mode,
      branch: newBranch,
      commit_sha,
      pr_url: pr.pr_url,
      pr_number: pr.pr_number,
      ...(extras ?? {}),
    });
  } catch (e) {
    hadError = true;
    // Fix 2: discard any partial writes the mutator may have flushed to disk
    if (branchCreated) {
      try { discardWorkingTreeChanges(ctx.repoPath); } catch { /* best effort */ }
    }
    if (e instanceof GitOpsError) {
      return { ok: false, error: { code: e.code, message: e.message, details: e.details } };
    }
    return err("UNKNOWN", `Unexpected error: ${(e as Error).message}`);
  } finally {
    // Fix 1: always restore the caller's original branch (on both success and error paths)
    if (branchCreated) {
      try { checkoutBranch(ctx.repoPath, originalBranch); } catch { /* best effort */ }
      // On error: also delete the empty/partial tp branch
      if (hadError) {
        try { deleteBranch(ctx.repoPath, newBranch); } catch { /* best effort */ }
      }
    }
  }
}
