name: Reset Dev Tracking Plans

on:
  release:
    types: [published]

jobs:
  initialize-matrix:
    if: contains(github.event.release.name, 'RESET_DEV')
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.parse_json.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load Tracking Plans Configuration for Dev Reset
        id: parse_json
        run: |
          MATRIX=$(jq -c '[.plans[] | {name, path, dev_secret}]' config/tracking-plans-config.json)
          echo "::set-output name=matrix::$MATRIX"

  reset-dev-tracking-plans:
    needs: initialize-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tracking_plan: ${{ fromJson(needs.initialize-matrix.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Reset Dev Tracking Plan Rules from Prod Source
        env:
          SEGMENT_API_KEY: ${{ secrets.SEGMENT_PUBLIC_API_TOKEN }}
          SEGMENT_TRACKING_PLAN_ID: ${{ secrets[matrix.tracking_plan.dev_secret] }}
          PLAN_DIR: plans/prod/${{ matrix.tracking_plan.path }}
        run: |
          echo "Resetting DEV tracking plan for ${{ matrix.tracking_plan.name }}"
          node scripts/reset-tracking-plan.js || echo "No changes detected"
      
      - name: Save Dev Tracking Plan Rules
        env:
          SEGMENT_API_KEY: ${{ secrets.SEGMENT_PUBLIC_API_TOKEN }}
          SEGMENT_TRACKING_PLAN_ID: ${{ secrets[matrix.tracking_plan.dev_secret] }}
          PLAN_DIR: plans/dev/${{ matrix.tracking_plan.path }}
        run: |
          echo "Saving DEV tracking plan for ${{ matrix.tracking_plan.name }}"
          node scripts/save-tracking-plan.js || echo "No changes detected"

      - name: Commit and Push Updated Dev Rules
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git pull origin main  # Ensure we're up to date
          git add plans/dev/${{ matrix.tracking_plan.path }}/current-rules*.json
          git commit -m "Update DEV rules for ${{ matrix.tracking_plan.name }} [skip ci]" || echo "No changes to commit"
          git push origin main
